export interface OverpassResponse {
    version: number;
    generator: string;
    elements: OSMFeature[];
}

export interface OSMFeature {
    type: string;
    tags: OSMProperties;
    lat: number;
    lon : number;
    id: string;
}

export type OSMAmenity =
    'bar' |
    'biergarten' |
    'cafe' |
    'fast_food' |
    'food_court' |
    'ice_cream' |
    'pub' |
    'restaurant' |
    'college' |
    'dancing_school' |
    'driving_school' |
    'first_aid_school' |
    'kindergarten' |
    'language_school' |
    'library' |
    'surf_school' |
    'toy_library' |
    'research_institute' |
    'training' |
    'music_school' |
    'school' |
    'traffic_park' |
    'university' |
    'bicycle_parking' |
    'bicycle_repair_station' |
    'bicycle_rental' |
    'bicycle_wash' |
    'boat_rental' |
    'boat_sharing' |
    'bus_station' |
    'car_rental' |
    'car_sharing' |
    'car_wash' |
    'compressed_air' |
    'vehicle_inspection' |
    'charging_station' |
    'driver_training' |
    'ferry_terminal' |
    'fuel' |
    'grit_bin' |
    'motorcycle_parking' |
    'parking' |
    'parking_entrance' |
    'parking_space' |
    'taxi' |
    'weighbridge' |
    'atm' |
    'payment_terminal' |
    'bank' |
    'bureau_de_change' |
    'money_transfer' |
    'payment_centre' |
    'baby_hatch' |
    'clinic' |
    'dentist' |
    'doctors' |
    'hospital' |
    'nursing_home' |
    'pharmacy' |
    'social_facility' |
    'veterinary' |
    'arts_centre' |
    'brothel' |
    'casino' |
    'cinema' |
    'community_centre' |
    'conference_centre' |
    'events_venue' |
    'exhibition_centre' |
    'fountain' |
    'gambling' |
    'love_hotel' |
    'music_venue' |
    'nightclub' |
    'planetarium' |
    'public_bookcase' |
    'social_centre' |
    'stage' |
    'stripclub' |
    'studio' |
    'swingerclub' |
    'theatre' |
    'courthouse' |
    'fire_station' |
    'police' |
    'post_box' |
    'post_depot' |
    'post_office' |
    'prison' |
    'ranger_station' |
    'townhall' |
    'bbq' |
    'bench' |
    'dog_toilet' |
    'dressing_room' |
    'drinking_water' |
    'give_box' |
    'lounge' |
    'mailroom' |
    'parcel_locker' |
    'shelter' |
    'shower' |
    'telephone' |
    'toilets' |
    'water_point' |
    'watering_place' |
    'sanitary_dump_station' |
    'recycling' |
    'waste_basket' |
    'waste_disposal' |
    'waste_transfer_station' |
    'animal_boarding' |
    'animal_breeding' |
    'animal_shelter' |
    'animal_training' |
    'baking_oven' |
    'clock' |
    'crematorium' |
    'dive_centre' |
    'funeral_hall' |
    'grave_yard' |
    'hunting_stand' |
    'internet_cafe' |
    'kitchen' |
    'kneipp_water_cure' |
    'lounger' |
    'marketplace' |
    'monastery' |
    'mortuary' |
    'photo_booth' |
    'place_of_mourning' |
    'place_of_worship' |
    'public_bath' |
    'public_building' |
    'refugee_site' |
    'vending_machine';

export interface OSMProperties {
    "@id": string;
    amenity: OSMAmenity;
    building?: string;
    "contact:website"?: string;
    name?: string;
    "ref:bag"?: string;
    source?: string;
    "source:date"?: string;
    start_date?: string;
    type?: string;
    website: string;
    "@geometry"?: string;
    "building:levels"?: string;
    healthcare?: string;
    operator?: string;
    wheelchair?: string;
    note?: string;
    phone?: string;
    "addr:city"?: string;
    "addr:housenumber"?: string;
    "addr:postcode"?: string;
    "addr:street"?: string;
    "building:colour"?: string;
    "building:material"?: string;
    "roof:levels"?: string;
    "roof:material"?: string;
    "roof:shape"?: string;
    social_facility?: string;
    "social_facility:for"?: string;
    image?: string;
    "addr:country"?: string;
    opening_hours?: string;
    internet_access?: string;
    "internet_access:fee"?: string;
    "internet_access:type"?: string;
    email?: string;
    fax?: string;
    "addr:housename"?: string;
    nursing_home?: string;
    "healthcare:speciality"?: string;
    check_date?: string;
    "check_date:opening_hours"?: string;
    "emergency:phone"?: string;
    alt_name?: string;
    height?: string;
    "toilets:wheelchair"?: string;
    emergency?: string;
    landuse?: string;
    old_name?: string;
    "contact:phone"?: string;
    atm?: string;
    wikidata?: string;
    smoking?: string;
    indoor?: string;
    level?: string;
    description?: string;
    "operator:wikidata"?: string;
    "building:level"?: string;
    "building:part"?: string;
    designation?: string;
    "wheelchair:description"?: string;
    "description:nl"?: string;
    beauty?: string;
    "opening_hours:signed"?: string;
    branch?: string;
    brand?: string;
    "contact:email"?: string;
    max_age?: string;
    min_age?: string;
    emergency_telephone_code?: string;
    "health_specialty:manual_therapy"?: string;
    "health_specialty:physiotherapy"?: string;
    "health_specialty:podo_therapy"?: string;
    "operator:website"?: string;
    "name:en"?: string;
    "name:tr"?: string;
    old_website?: string;
    "contact:facebook"?: string;
    "contact:instagram"?: string;
    religion?: string;
    abandoned?: string;
    "contact:mobile"?: string;
    "operator:type"?: string;
    "currency:XBT"?: string;
    "payment:lightning"?: string;
    "payment:lightning_contactless"?: string;
    "payment:onchain"?: string;
    "survey:date"?: string;
    "source:website"?: string;
    facebook?: string;
    twitter?: string;
    alt_phone?: string;
    official_name?: string;
    mobile?: string;
    "contact:fax"?: string;
    "name:prefix"?: string;
    "name:nl"?: string;
    url?: string;
    "phone:NL"?: string;
    "phone:emergency"?: string;
    short_name?: string;
    "contact:whatsapp"?: string;
    "opening_hours:url"?: string;
    dispensing?: string;
    "addr:unit"?: string;
    fixme?: string;
    "addr:province"?: string;
    wikipedia?: string;
    office?: string;
    source_ref?: string;
    "name:de"?: string;
    "official_name:brand"?: string;
    "reservation:covid19"?: string;
    "language:de"?: string;
    "language:en"?: string;
    "language:nl"?: string;
    pharmacy?: string;
    "phone:opening_hours"?: string;
    "contact:twitter"?: string;
    comment?: string;
    "brand:wikidata"?: string;
    reservation?: string;
    "blokker:id"?: string;
    "name:-2021-10"?: string;
    "addr:suburb"?: string;
    "source:name"?: string;
    "website:note"?: string;
    capacity?: string;
    hospital?: string;
    "contact:phone:emergency"?: string;
    huisartspraktijk?: string;
    "description:en"?: string;
    "description:fy"?: string;
    clinic?: string;
    "medical_system:western"?: string;
    "payment:american_express"?: string;
    "payment:apple_pay"?: string;
    "payment:cards"?: string;
    "payment:contactless"?: string;
    "payment:mastercard_contactless"?: string;
    notes?: string;
    operational_status?: string;
    "staff_count:doctors"?: string;
    "staff_count:nurses"?: string;
    layer?: string;
    outdoor_seating?: string;
    appointment?: string;
    "addr:floor"?: string;
    "health_person:type"?: string;
    "health_specialty:dermatology"?: string;
    service_times?: string;
    temporary?: string;
    vaccination?: string;
    delivery?: string;
    "phone:delivery"?: string;
    opening_date?: string;
    "payment:cash"?: string;
    "payment:credit_cards"?: string;
    "payment:debit_cards"?: string;
    "ref:gers"?: string;
}