import type { Metadata } from "next";
import "./globals.css";
import { Familjen_Grotesk, Inter } from 'next/font/google'
import { cn } from '@/lib/utils';
import Link from 'next/link';
import { TooltipProvider } from '@/components/ui/tooltip';
import { RedButtonProvider } from '@/components/RedButton/context';
import { NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger } from '@/components/ui/navigation-menu';
import hierarchy from '@are-we-dependent/data/hierarchy';
import { getIconForCategory } from '@/lib/icons';
import RedButton from '@/components/RedButton';
import Menu from './menu';

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })
const familjen = Familjen_Grotesk({ subsets: ['latin'], weight: 'variable' })

export const metadata: Metadata = {
    title: "Zijn we al autonoom?",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <title>Zijn we al autonoom?</title>
            </head>
            <body className={cn(inter.className, familjen.className, 'bg-blue-50 text-blue-900')}>
                <RedButtonProvider>
                    <TooltipProvider>
                        <Menu />
                        <main className="max-w-[1280px] mx-auto xl:px-0 p-8">
                            {children}
                        </main>
                    </TooltipProvider>
                </RedButtonProvider>
            </body>
        </html>
    );
}
